
use pruebas;
truncate table respuestas;
-- INSERT RESPUESTAS Geografia
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (1,'Andorra',true),(1,'Albania', false),(1,'Alemania', false),(1,'Andalucía',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (2,'Barcelona',true),(2,'Girona',false),(2,'Lleida',false),(2,'Tarragona',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (3,'Chile',true),(3,'Dominicana',false),(3,'Ecuador',false),(3,'Argentina',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (4,'Dublín',true),(4,'Glasgow',false),(4,'Limerick',false),(4,'Tallín',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (5,'Estrecho de Gibraltar',true),(5,'Estrecho de Ormuz',false),(5,'Estrecho de Magallanes',false),(5,'Estrecho de Bering',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (6,'Finlandia',true),(6,'Estonia',false),(6,'Letonia',false),(6,'Lituania',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (7,'Groenlandia',true),(7,'Antartida',false),(7,'Barbados',false),(7,'Turcos Y Caicos',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (8,'Himalaya',true),(8,'Karakórum',false),(8,'Andes ',false),(8,'Alpes',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (9,'Islandia',true),(9,'Irlanda',false),(9,'Islas Marchall',false),(9,'Irán',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (10,'Japón',true),(10,'Corea del Norte',false),(10,'Corea del Sur',false),(10,'Taiwán',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (11,'Kenia',true),(11,'Sudán',false),(11,'Libia',false),(11,'Argelia',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (12,'Londres',true),(12,'Manchester',false),(12,'Liverpool',false),(12,'Oxford',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (13,'Mar Mediterraneo',true),(13,'Mar Báltico',false),(13,'Mar Negro',false),(13,'Mar Pacífico',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (14,'Noruega',true),(14,'Finlandia',false),(14,'Nicaragua',false),(14,'Nairobi',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (15,'Óasis',true),(15,'Erial',false),(15,'Yermo',false),(15,'Oáramo',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (16,'Panamá',true),(16,'Eipto',false),(16,'Alemania',false),(16,'Grecia',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (17,'Qatar',true),(17,'Comoras',false),(17,'Yibuti',false),(17,'Qomán',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (18,'Rusia',true),(18,'Estados Unidos de America',false),(18,'China',false),(18,'India',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (19,'Suiza',true),(19,'Suecia',false),(19,'Serbia',false),(19,'Mónaco',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (20,'Tasmania',true),(20,'Tenerife',false),(20,'Trinidad',false),(20,'Tahití',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (21,'Uruguay',true),(21,'Unduras',false),(21,'Perú',false),(21,'Uganda',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (22,'Venezuela',true),(22,'Cuba',false),(22,'Republica Dominicana',false),(22,'Haití',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (23,'Wales',true),(23,'Gales',false),(23,'Wengland',false),(23,'Escotland',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (24,'Xi Jiang',true),(24,'Xamur',false),(24,'Xhang Jiang',false),(24,'Huang  He',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (25,'Yucatán',true),(25,'Baja California',false),(25,'Yamal',false),(25,'Yuno',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (26,'Rio Zambeze',true),(26,'Rio Nilo',false),(26,'Rio Congo',false),(26,'Rio Níger',false);

-- INSERT RESPUESTAS Historia
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (27,'Adolf',true),(27,'Otto von Bismarck',false),(27,'Theobald von Bethmann-Hollweg',false),(27,'Federico III',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (28,'Bizantino',true),(28,'Carolingio ',false),(28,'Imperio Romano Germánico',false),(28,'Califato Islámico',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (29,'Cristobal Colón',true),(29,'Juan Sebastián Elcano',false),(29,'Zheng He',false),(29,'Don Quijote',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (30,'Dictador',true),(30,'Rey',false),(30,'Mesías',false),(30,'César',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (31,'Egipcia',true),(31,'Mesopotámica',false),(31,'Hindú',false),(31,'China',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (32,'Faraon',true),(32,'Visir',false),(32,'Sesh',false),(32,'Hem-Netjer',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (33,'Galileo Galilei',true),(33,'Pierre-Simon Laplace',false),(33,'Leonhard Euler',false),(33,'Joseph-Louis Lagrange',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (34,'Heródoto de Halicarnaso',true),(34,'Sima Qian',false),(34,'Tucídides',false),(34,'Leopold von Ranke',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (35,'Inca',true),(35,'Imperio Mongol',false),(35,'Indaemon',false),(35,'Insopetacol',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (36,'Juana de Arco',true),(36,'Jeanne Moreau',false),(36,'Juana III de Navarra',false),(36,'Jacqueline de Romilly',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (37,'Karl Marx',true),(37,'KarloMagno',false),(37,'Kartin Klartón',false),(37,'Kalbert den-chein',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (38,'Lenin',true),(38,'León Trotsky',false),(38,'Lstalin',false),(38,'Léstor Majnó',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (39,'Medievo',true),(39,'Mesolítico',false),(39,'Minoico',false),(39,'Meiji',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (40,'Núremberg',true),(40,'Berlín',false),(40,'Colonia',false),(40,'Bremen',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (41,'Omaní',true),(41,'Orgus',false),(41,'Odris',false),(41,'Otomano',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (42,'Pompeya',true),(42,'Ponstantinopla',false),(42,'Préveris',false),(42,'Palejandría',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (43,'Quing',true),(43,'Queng',false),(43,'Quange',false),(43,'Quash',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (44,'Revolución Francesa',true),(44,'Revolución Industrial',false),(44,'Revolución Agricola',false),(44,'Revolución Marchotamica',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (45,'Socrates',true),(45,'Séneca',false),(45,'Simplício de Cilicia',false),(45,'Spinoza',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (46,'Tutankamon',true),(46,'Tutmosis',false),(46,'Tiy',false),(46,'Tauseret',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (47,'URSS',true),(47,'UCM',false),(47,'UKC',false),(47,'UAO',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (48,'Vikingos',true),(48,'Varvaros',false),(48,'Vesugos',false),(48,'Vomberios',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (49,'Duque de Wellington',true),(49,'Duque de Willgham',false),(49,'Duque de Wallstreet',false),(49,'Wallrtin',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (50,'Dinastia Xia',true),(50,'Xen',false),(50,'Xuan',false),(50,'Xion',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (51,'Dinastia Yuan',true),(51,'Yutecan',false),(51,'Yena',false),(51,'Yo-hun',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (52,'Dinastia Zhou',true),(52,'Zeng',false),(52,'Zhos',false),(52,'Zeus',false);

-- INSERT RESPUESTAS Música
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (53,'ABBA',true),(53,'Abel',false),(53,'Adele',false),(53,'Args',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (54,'Batería',true),(54,'Bandoneón',false),(54,'Bongó',false),(54,'Bombo',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (55,'Chopín',true),(55,'Cornelius',false),(55,'Corellí',false),(55,'Cavallí',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (56,'DJ',true),(56,'DP',false),(56,'Disyóquey ',false),(56,'Deepath',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (57,'Elvis Presley',true),(57,'Eddie Cochran',false),(57,'Ella Fitzgerald',false),(57,'Erroll Garner',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (58,'Flamenco',true),(58,'Flojta',false),(58,'Flopa',false),(58,'Fralapo',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (59,'Guitarra',true),(59,'Guitarrón',false),(59,'Guzheng',false),(59,'Gaita',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (60,'Händel',true),(60,'Hudwig van Beethoven',false),(60,'Hélix Mendelssohn',false),(60,'Hobert Schumann',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (61,'Iglesias',true),(61,'ISman',false),(61,'Irnandéz',false),(61,'Irfaldo',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (62,'Jackson, Michael',true),(62,'Jordan, Michael',false),(62,'Thomas Jefferson',false),(62,'J.K. Rowling',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (63,'K-Pop',true),(63,'K-pap',false),(63,'Kuang',false),(63,'Kosh',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (64,'Lady Gaga',true),(64,'Lemur',false),(64,'Leonardo Da',false),(64,'Lana del Rey',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (65,'Mozart',true),(65,'Meethoven',false),(65,'Mrahms',false),(65,'Leonardo da Vinci',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (66,'Nota',true),(66,'Nudo',false),(66,'Nitx',false),(66,'Narc',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (67,'Orquesta',true),(67,'Omaní',false),(67,'Octeto',false),(67,'Orchesta',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (68,'Pop',true),(68,'Punk',false),(68,'Plena',false),(68,'Post-Rock',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (69,'Queen',true),(69,'Queen-Bee',false),(69,'Quilapayún',false),(69,'Queens of the Stone Age',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (70,'Rihanna',true),(70,'Rosalia',false),(70,'Raye',false),(70,'Ruth Brown',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (71,'Saxofón',true),(71,'Sheng',false),(71,'Steelpan',false),(71,'Surdo',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (72,'Tempo',true),(72,'Tass',false),(72,'Trhag',false),(72,'Tiempo',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (73,'Ukelele',true),(73,'Umbrago',false),(73,'Ucarto',false),(73,'Ucharango',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (74,'Viiolín',true),(74,'Viola',false),(74,'Violonchelo',false),(74,'Voctobajo',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (75,'Woodstock',true),(75,'WaterBomb',false),(75,'Womad',false),(75,'Wacken Open Air',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (76,'Xilófono',true),(76,'Xalam',false),(76,'Xuan',false),(76,'Xaphoon',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (77,'Yoko ono',true),(77,'Yinka Shonibare',false),(77,'Yasuke Yokoo',false),(77,'Yayoi Kusama',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (78,'Zamba',true),(78,'Zumba',false),(78,'Zeze',false),(78,'Zalga',false);

-- INSERT RESPUESTAS Informatica
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (79,'AMD',true),(79,'Apple',false),(79,'Amazon',false),(79,'Amanico',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (80,'BOOLEAN',true),(80,'BOOL',false),(80,'Binario',false),(80,'Bash',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (81,'CPU',true),(81,'Cerebro de Ordenador',false),(81,'Cloud Computing',false),(81,'CRUD',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (82,'Disco Duro',true),(82,'DevOps',false),(82,'DNS',false),(82,'DRAM',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (83,'Email',true),(83,'Ebox',false),(83,'eBay',false),(83,'Eshock',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (84,'FaceBook',true),(84,'Flicker',false),(84,'Fotolog',false),(84,'Friendster',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (85,'Gigabyte',true),(85,'GetaByte',false),(85,'Gega-Byte',false),(85,'Giga',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (86,'Hackers',true),(86,'Hacakroom',false),(86,'Hasher',false),(86,'Harper',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (87,'Internet',true),(87,'Intranet',false),(87,'Infranet',false),(87,'Instread',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (88,'JoyStick',true),(88,'Joyful',false),(88,'Joy-Boy',false),(88,'JoyMack',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (89,'KeyBoard',true),(89,'KeyShortcut',false),(89,'Keymax',false),(89,'Key',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (90,'Linux',true),(90,'Lisp Machine OS',false),(90,'Lisa OS',false),(90,'Lumina',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (91,'Microsoft',true),(91,'Mattel',false),(91,'Marvel',false),(91,'Mastercard',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (92,'Nube',true),(92,'Network',false),(92,'NASH',false),(92,'NAS',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (93,'Online',true),(93,'Offline',false),(93,'Outline',false),(93,'OUTInline',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (94,'Píxel',true),(94,'Pixar',false),(94,'Plex',false),(94,'Presix',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (95,'QWERTY',true),(95,'Query spanish',false),(95,'Qamish',false),(95,'QYTREW',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (96,'RAM',true),(96,'VRAM',false),(96,'RACK',false),(96,'Rush',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (97,'SPAM',true),(97,'Splash',false),(97,'Span',false),(97,'Saas',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (98,'Twitter',true),(98,'Threads',false),(98,'Thrag',false),(98,'Thanos',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (99,'URL',true),(99,'UML',false),(99,'UHL',false),(99,'UJP',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (100,'Virus',true),(100,'Vram',false),(100,'Vasup',false),(100,'Virión',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (101,'Wifi',true),(101,'WIreless',false),(101,'Wtoth',false),(101,'Wack',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (102,'Xbox',true),(102,'Xintendo',false),(102,'Xdeck',false),(102,'Xamex',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (103,'Yottabyte',true),(103,'Yute',false),(103,'Yurr',false),(103,'YuseByte',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (104,'Zoom',true),(104,'Google Zeet',false),(104,'Zistsi Meet',false),(104,'Zaam',false);

-- INSERT RESPUESTAS Entretenimiento
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (105,'Animal Crossing',true),(105,'Assassin´s Creed',false),(105,'Age of Empires',false),(105,'Arkham',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (106,'Batman',true),(106,'Bruce Wayne',false),(106,'Bane',false),(106,'Banner',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (107,'Cartoon Network',true),(107,'Comedy Central',false),(107,'CNN',false),(107,'Comedy Central',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (108,'Disney',true),(108,'Discovery Chanel',false),(108,'DreamWorks',false),(108,'Digital Arts',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (109,'E.T.',true),(109,'Elsa',false),(109,'Epona',false),(109,'Edward',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (110,'Fast & Furious',true),(110,'Feed For speed',false),(110,'Fast & Food',false),(110,'Fart',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (111,'Godzilla',true),(111,'Gamera',false),(111,'Gex',false),(111,'Ganon',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (112,'Harry Potter',true),(112,'Hasta',false),(112,'Harsel',false),(112,'Hermion',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (113,'Interestelar',true),(113,'Illmary Project',false),(113,'Inception',false),(113,'Indiana Jones',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (114,'James Bond',true),(114,'John Wick',false),(114,'Jack Sparrow',false),(114,'Joker',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (115,'Kirby',true),(115,'Kratos',false),(115,'Kazuya Mishima',false),(115,'Kamek',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (116,'Looney Tunes',true),(116,'Ladybug',false),(116,'Little Einsteins',false),(116,'LazyTown',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (117,'Mickey Mouse',true),(117,'Micey',false),(117,'Mikachu',false),(117,'Marchu',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (118,'Netflix',true),(118,'Metflix',false),(118,'Nex',false),(118,'Nofliz',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (119,'Olaf',true),(119,'Olax',false),(119,'Orlax',false),(119,'Omar',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (120,'Piratas del Caribe',true),(120,'Piratas del Sahara',false),(120,'Piratas del mediterraneo',false),(120,'Piratas',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (121,'Quentin Tarantino',true),(121,'Quasar',false),(121,'QuickSilver',false),(121,'Qello Concerts',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (122,'Rambo',true),(122,'Rocky Balboa',false),(122,'Ray Tango',false),(122,'Rush Hunson',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (123,'Star Wars',true),(123,'Star Destructor',false),(123,'Stack Poor',false),(123,'Star Treek',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (124,'Titanic',true),(124,'Tunberry',false),(124,'The Terror',false),(124,'Trinidad',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (125,'Up',true),(125,'Uncle Topolino',false),(125,'Ume',false),(125,'University',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (126,'Vikingos',true),(126,'Valvet',false),(126,'V',false),(126,'Gen V',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (127,'Warner Bros',true),(127,'Way Back',false),(127,'Warmer Beach',false),(127,'Widow Black',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (128,'X-Men',true),(128,'X.Japan',false),(128,'Xiu Xiu',false),(128,'X-Fantastic',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (129,'Yu-Gi-Oh!',true),(129,'Yuru Camp',false),(129,'Yozakura',false),(129,'Yojouhan',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (130,'Zombie',true),(130,'Zoro',false),(130,'Zelda',false),(130,'Zekrom',false);

-- INSERT RESPUESTAS Deportes
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (131,'Arsenal',true),(131,'Atletico de Madrid',false),(131,'Ajax de Ámsterdam',false),(131,'A.C. Milan',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (132,'Barça',true),(132,'Bayern de Munich',false),(132,'Borussia Dortmund',false),(132,'Benfica',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (133,'Champions League',true),(133,'Copa Libertadores',false),(133,'Copa del Rey',false),(133,'Copa Africana',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (134,'Dončić, Luka',true),(134,'Diego Armando Maradona',false),(134,'Dirk Nowitzki',false),(134,'Dennis Rodman',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (135,'España',true),(135,'Estonia',false),(135,'Etiopía',false),(135,'Eslovenia',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (136,'F1',true),(136,'F2',false),(136,'F5',false),(136,'Ferrari Land',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (137,'Gasol',true),(137,'Gabi',false),(137,'Guerrero Chus',false),(137,'Gento',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (138,'Hockey',true),(138,'HandBall',false),(138,'Hoverboard Racing',false),(138,'Huttball',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (139,'Iker Casillas',true),(139,'Iniesta',false),(139,'Ibrahimović',false),(139,'Iverson',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (140,'Judo',true),(140,'Jiu-Jitsu',false),(140,'Jinetismo',false),(140,'Javelin',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (141,'Kart',true),(141,'Kartcross',false),(141,'superkarts',false),(141,'karts Copa piston',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (142,'Lionel Messi',true),(142,'LeBron James',false),(142,'Lamine Yamal',false),(142,'Luka Modrić',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (143,'Marc Marquéz',true),(143,'Mbappé',false),(143,'Mohamed salah',false),(143,'Maverick Viñales',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (144,'Natación',true),(144,'Natación artistica',false),(144,'Nascar',false),(144,'Nordic Walking',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (145,'Olimpiadas',true),(145,'Olympus Rally',false),(145,'Orange Bowl',false),(145,'Olimpiadas de Ajedrez',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (146,'Puyol',true),(146,'Pelé',false),(146,'Pau Gasol',false),(146,'Patrick Ewing',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (147,'Qatar',true),(147,'Quito',false),(147,'Quanzhou',false),(147,'Quebec',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (148,'Ronaldo',true),(148,'Ronaldinho',false),(148,'Ronaldo Nazario',false),(148,'Rafael Nadal',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (149,'Surf',true),(149,'Skateboarding',false),(149,'Snowboard',false),(149,'SpeedBall',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (150,'Tour de Francia',true),(150,'Torneo de Madrid',false),(150,'Torneo de Candidatos',false),(150,'Triple Corona',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (151,'UEFA',true),(151,'UFC',false),(151,'UWW',false),(151,'UCI',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (152,'Volei',true),(152,'Vela',false),(152,'Vuelo sin Motor',false),(152,'Volteo',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (153,'Williams',true),(153,'Wingston',false),(153,'Willington',false),(153,'Wesh',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (154,'Xabi Alonso',true),(154,'Xavi Hernández',false),(154,'Xavi Forés',false),(154,'Xavier Siméon',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (155,'Yankees',true),(155,'Yonki',false),(155,'Yenkins',false),(155,'Yenkeens',false);
INSERT INTO RESPUESTAS(id_pregunta, texto_respuesta, correcta) values (156,'ZINEDINE ZIDANE',true),(156,'Zlatan Ibrahimović',false),(156,'Zico',false),(156,'Zanardi',false);

-- Ejecuta esta linea para comprobar el funcionamiento
select * from respuestas;