@startuml logica

start

:Escena 3D;

:Tirar dado;

:Mover personaje animado;

:Detectar casilla;

:Cargar pregunta;

:Pregunta;

:Mostrar opciones;

:Iniciar temporizador;

if (¿Correcta?) then (SI)
  :Seguir;
else (NO)
  :Perder vida;
endif

if (¿Vidas > 0?) then (SI)
  :Siguiente turno;
else (NO)
  :Game Over;
endif

stop

@enduml