version: '3.8'

services:
  # Contenedor de la Base de Datos
  base_datos:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hpednatura
      MYSQL_DATABASE: proyectoabp_db
      MYSQL_USER: hpednatura
      MYSQL_PASSWORD: hpednatura
    ports:
      - "3306:3306"
    volumes:
      - datos_mysql:/var/lib/mysql

  # Contenedor de Node.js
  servidor_node:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "8080:3000"
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm start"
    depends_on:
      - base_datos

volumes:
  datos_mysql:
